### ISSUE TITLE
Mehr Informationen über gesperrte Domains: Hoster und Land

### ISSUE THREAD

**Issue by mritzmann** [dnszensur/dnszensur-crawler#4]
Es wäre Interessant, bei welchem Hoster (bzw. im welchem AS) und in welchem Land die gesperrten Domains gehostet werden. Dazu könnte man die ip-api.com API nutzen.

---

http://ip-api.com/json/google.com?fields=country,as

```
{"as":"AS15169 Google Inc.","country":"United States"}
```

> Our system will automatically ban any IP addresses doing over 150 requests per minute.

---

- [x] Neue Spalte in DB anlegen
- [x] Abfrage in `if ($determined_censoring_state != $row->$censoring_state_isp)` einbauen
- [x] dnszensur-api entsprechend anpassen https://github.com/dnszensur/dnszensur-api/pull/5
- [x] dnszensur-web entsprechend anpassen: Neue Spalte hinzufügen https://github.com/dnszensur/dnszensur-web/pull/44
- [ ] example db anpassen
- [x] dnszensur-web: FAQ ergänzen

**Comment by AnBuKu** [comment]
Nice. Good idea adding more information about domain hoster and country of hosting company/ server.

**Comment by mritzmann** [comment]
Information about hosting provider and server location is now available on dnszensur.ch
